### ISSUE TITLE
Plugin to set my status always online

### ISSUE THREAD

**Issue by temporhodes** [UsergeTeam/Userge-Plugins#137]
Hello guys.
is there any way or plugin that i can change my status to online even when i'm not ?

Thanks.

**Comment by SurajRaj4542** [comment]
Can Use your userbot...

you can schedule your userbot,,, to do some task.. everytime it does your status will change to online 🟢

**Comment by SurajRaj4542** [comment]
> Hello guys.
> is there any way or plugin that i can change my status to online even when i'm not ?
> 
> Thanks.

Can Use your userbot...

you can schedule your userbot,,, to do some task.. everytime it does your status will change to online 🟢

**Comment by temporhodes** [comment]
> > Hello guys.
> > is there any way or plugin that i can change my status to online even when i'm not ?
> > Thanks.
> 
> Can Use your userbot...
> 
> you can schedule your userbot,,, to do some task.. everytime it does your status will change to online 🟢

I am using userge.but dont know how to do that.

**Comment by SurajRaj4542** [comment]
> > > Hello guys.
> > > is there any way or plugin that i can change my status to online even when i'm not ?
> > > Thanks.
> > 
> > 
> > Can Use your userbot...
> > you can schedule your userbot,,, to do some task.. everytime it does your status will change to online 🟢
> 
> I am using userge.but dont know how to do that.

Like .. set cmds for userbot in schedule in some LOG_GROUPS . So , If your bot will perform schedule task your status will change to online simultaneously

**Comment by rking32** [comment]
telegram may give you a **gift** called **ban**. so closing ...

**Comment by Harsh-br0** [comment]
> is there any way or plugin that i can change my status to online even when i'm not ?


https://github.com/pyrogram/pyrogram/issues/513#issuecomment-715403976 👀
