### ISSUE TITLE
Plugin to get telegram video from direct url

### ISSUE THREAD

**Issue by newaccforhc** [UsergeTeam/Userge-Plugins#143]
I can’t find any relevant plugin which can send video file on telegram from the direct download link I provide..

**Comment by rking32** [comment]
@newaccforhc are you talking about how to upload a telegram video using link ?

**Comment by newaccforhc** [comment]
Yeah...

**Comment by rking32** [comment]
try `.upload [direct_link]` thats it. further read `.help upload`

**Comment by newaccforhc** [comment]
Oof.. sorry for being dumb issue 😂...
