### ISSUE TITLE
Anigrab Plug-in request

### ISSUE THREAD

**Issue by newaccforhc** [UsergeTeam/Userge-Plugins#144]
Any possibility to get a plug-in for this tool?:
https://github.com/ngomile/anigrab

Thank you!

**Comment by rking32** [comment]
what about this one -> https://github.com/UsergeTeam/Userge-Plugins/blob/master/plugins/anilist.py ?
if you have enabled unofficial, you can try `.help anilist`

**Comment by newaccforhc** [comment]
That's only for getting info, images and related info...
The module I sent is for downloading episodes.

**Comment by Krishna-Singhal** [comment]
> Any possibility to get a plug-in for this tool?:
> https://github.com/ngomile/anigrab
> 
> Thank you!

This Repo Using Aria2 and we can't add aria2 in Userge , Closing this issue should be better ☺️

**Comment by rking32** [comment]
at least send `python` library
