### ISSUE TITLE
FLAC/320/256/128Kbps Quality selection for Spotdl/Spot*fy links via Deezloader

### ISSUE THREAD

**Issue by Wileyfox-F1** [UsergeTeam/Userge-Plugins#198]
**This feature was available in the Deezloader plugin previously**, don't know what happened after the deployment via helper script to the newer version! If you can reinclude this feature in either Spotdl/Deezloader plugin, it would be much helpful. Now it's not possible to download **FLAC Format files from Spot*fy** 

_Thank you for this awesome project_

**Comment by TomyPrs** [comment]
Issue solved after this https://github.com/UsergeTeam/Userge-Plugins/pull/205
