### ISSUE TITLE
Add Thumbnail support for IMDB

### ISSUE THREAD

**Issue by theRay1s** [UsergeTeam/Userge-Plugins#32]
Is it possible to add support for setting custom thumbnail in IMDb plugin

like

<b>Title</b> 🎬: <a href="#IMDB_URL">#TITLE</a>

<i>Quality</i> 💿: 720p Blu-ray

<b>Genre</b>: #GENRE
<i>Rating</i> ⭐️: <code>#RATING</code>
<b>Release Info</b>: #RELEASE_INFO

<i>Audio</i> 🔊:  #Hindi  #LANGUAGE
<b>Cast info</b> 🤹‍♂ #CAST_INFO
<b>Story Line</b>: #STORY_LINE

**Comment by rking32** [comment]
yes, its possible @Phyco-Ninja

**Comment by theRay1s** [comment]
@rking32 

and better merge these into one 

</code>\n<b>Director : </b><code>' + director +
            '</code>\n<b>Writer : </b><code>' + writer +
            '</code>\n<b>Stars : </b><code>' + stars +

like
<b>cast info : </b><code>' + #cast_info + '</code>

**Comment by rking32** [comment]
@theRay1s now ok ? (imdb command)

**Comment by theRay1s** [comment]
@rking32 thanks for taking my suggestion serious
