### ISSUE TITLE
torrent leech plugin

### ISSUE THREAD

**Issue by qorcfotian** [UsergeTeam/Userge-Plugins#42]
may tihs helps: https://github.com/SpEcHiDe/UniBorg/blob/master/stdplugins/aria_two.py

**Comment by rking32** [comment]
what should i tell you :thinking: 

check this -> https://github.com/UsergeTeam/Userge/issues/50

**Comment by Phyco-Ninja** [comment]
🤔 well i habe something

**Comment by Phyco-Ninja** [comment]
@qorcfotian check this sar and understand it plox 😊 https://telegra.ph/file/6b55736ea0d14cb8df1c4.jpg

**Comment by qorcfotian** [comment]
ok thank you :)
