### ISSUE TITLE
deezloader - download artist 

### ISSUE THREAD

**Issue by ghost** [UsergeTeam/Userge-Plugins#46]
in original deezloader, we can download all songs from an artist.
in this plugin, we can not. please add this feature.

**Comment by Phyco-Ninja** [comment]
> in original deezloader, we can download all songs from an artist.
> in this plugin, we can not. please add this feature.

If you are talking about deezload application, this is not readable. 
Current deezloader plugin is using `deezloader` Module, and it doesn't provide downloading all musics from a Artist. Even if it provided i can't give it 😴. Lot of Flood Waits sar.
