### ISSUE TITLE
deezloader - locking other commands

### ISSUE THREAD

**Issue by qorcfotian** [UsergeTeam/Userge-Plugins#47]
when give the command: "`.deezload * FLAC`" deezload locks other commands.
try deezload a song and give `.ls` or `.alive` command. you will understand what i'm talking about.

**Comment by Phyco-Ninja** [comment]
> when give the command: "`.deezload * FLAC`" deezload locks other commands.
> try deezload a song and give `.ls` or `.alive` command. you will understand what i'm talking about.

Running  `.deezload` gives https://t.me/usergeot/193818 😐🤐

**Comment by rking32** [comment]
> when give the command: "`.deezload * FLAC`" deezload locks other commands.
> try deezload a song and give `.ls` or `.alive` command. you will understand what i'm talking about.

@qorcfotian did you mean block whole userbot by deezloader commands ?

**Comment by qorcfotian** [comment]
> 
> 
> > when give the command: "`.deezload * FLAC`" deezload locks other commands.
> > try deezload a song and give `.ls` or `.alive` command. you will understand what i'm talking about.
> 
> @qorcfotian did you mean block whole userbot by deezloader commands ?

yes. deezload command blocks "userge commands" like .ls or .alive.

**Comment by Phyco-Ninja** [comment]
> when give the command: "`.deezload * FLAC`" deezload locks other commands.
> try deezload a song and give `.ls` or `.alive` command. you will understand what i'm talking about.

dude is it still locking 😐😂?

**Comment by Akshaygit1** [comment]
Today i faced this too 😐
I was downloading a big playlist, so i think it's because of load? Which freezes bot.

**Comment by rking32** [comment]
ohk, now it confirmed :+1:
