### ISSUE TITLE
Fix split file when downloads

### ISSUE THREAD

**Issue by Mijinikopv** [UsergeTeam/Userge-Plugins#61]
The file is splitted when download and it was take much time to combine back the file each time i use the direct link.It will be easy if it combine the file auto when download the file.

**Comment by rking32** [comment]
yeah true, we are gonna drop smartDL :+1:

**Comment by Mijinikopv** [comment]
😊😊👍👍

**Comment by rking32** [comment]
closing because of not related to this repo and we can continue this topic on https://github.com/UsergeTeam/Userge/issues/58
