### ISSUE TITLE
[Plugin Request] Animated sticker to GIF

### ISSUE THREAD

**Issue by Akshaygit1** [UsergeTeam/Userge-Plugins#62]
Plugin to convert animated stickers to gif.

**Comment by udaythefreelancer** [comment]
Bro this is not an issue it's a pull request, post in pull request

**Comment by rking32** [comment]
also userge has ig :thinking: , @Phyco-Ninja

**Comment by Akshaygit1** [comment]
> Bro this is not an issue it's a pull request, post in pull request

Wait what :o how's this pull request? I'm requesting for new plugin not submitting plugin.

**Comment by Akshaygit1** [comment]
> also userge has ig  , @Phyco-Ninja

I thought same but couldn't find any such plugin/commands :/

**Comment by Phyco-Ninja** [comment]
> also userge has ig  , @Phyco-Ninja

Nope it doesn't have it. But yes, by using lottie we can convert animated sticker to gif

**Comment by Harsh-br0** [comment]
> also userge has ig  , @Phyco-Ninja

It possibly hab
If users know some eval and lottie😶

**Comment by rowdy-hero** [comment]
@Phyco-Ninja peru sar can do it 😗

**Comment by Phyco-Ninja** [comment]
> Plugin to convert animated stickers to gif.

https://github.com/friendly-telegram/modules-repo/blob/master/stickers.py#L261 Try ur luck
