### ISSUE TITLE
Lydia Crash

### ISSUE THREAD

**Issue by Bilibox** [UsergeTeam/Userge-Plugins#80]
> Traceback (most recent call last):
>2020-07-14T10:42:59.144224+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/runpy.py", line 194, in >_run_module_as_main
>2020-07-14T10:42:59.145330+00:00 app[worker.1]:     return _run_code(code, main_globals, None,
>2020-07-14T10:42:59.145368+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/runpy.py", line 87, in _run_code
>2020-07-14T10:42:59.145628+00:00 app[worker.1]:     exec(code, run_globals)
>2020-07-14T10:42:59.145663+00:00 app[worker.1]:   File "/app/userge/__main__.py", line 14, in <module>
>2020-07-14T10:42:59.145896+00:00 app[worker.1]:     userge.begin()
>2020-07-14T10:42:59.145927+00:00 app[worker.1]:   File "/app/userge/core/client.py", line 175, in begin
>2020-07-14T10:42:59.146182+00:00 app[worker.1]:     run(self.start())
>2020-07-14T10:42:59.146207+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/nest_asyncio.py", line 59, in run_until_complete
>2020-07-14T10:42:59.151016+00:00 app[worker.1]:     return f.result()
>2020-07-14T10:42:59.151058+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/asyncio/futures.py", line 178, in result
>2020-07-14T10:42:59.152401+00:00 app[worker.1]:     raise self._exception
>2020-07-14T10:42:59.152437+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/asyncio/tasks.py", line 280, in __step
>2020-07-14T10:42:59.153014+00:00 app[worker.1]:     result = coro.send(None)
>2020-07-14T10:42:59.153017+00:00 app[worker.1]:   File "/app/userge/core/client.py", line 161, in start
>2020-07-14T10:42:59.153286+00:00 app[worker.1]:     await self._load_plugins()
>2020-07-14T10:42:59.153332+00:00 app[worker.1]:   File "/app/userge/core/client.py", line 84, in _load_plugins
>2020-07-14T10:42:59.153473+00:00 app[worker.1]:     await self.load_plugin(name)
>2020-07-14T10:42:59.153477+00:00 app[worker.1]:   File "/app/userge/core/client.py", line 66, in load_plugin
>2020-07-14T10:42:59.153688+00:00 app[worker.1]:     importlib.import_module(f"userge.plugins.{name}"))
>2020-07-14T10:42:59.153714+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/importlib/__init__.py", line 127, in import_module
>2020-07-14T10:42:59.153863+00:00 app[worker.1]:     return _bootstrap._gcd_import(name[level:], package, level)
>2020-07-14T10:42:59.153867+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
>2020-07-14T10:42:59.154131+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>2020-07-14T10:42:59.154294+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>2020-07-14T10:42:59.160252+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
>2020-07-14T10:42:59.160623+00:00 app[worker.1]:   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
>2020-07-14T10:42:59.160910+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>2020-07-14T10:42:59.161229+00:00 app[worker.1]:   File "/app/userge/plugins/unofficial/lydia.py", line 153, in <module>
>2020-07-14T10:42:59.161680+00:00 app[worker.1]:     @userge.on_filters(
>2020-07-14T10:42:59.161801+00:00 app[worker.1]: TypeError: on_filters() got an unexpected keyword argument 'check_client'

crash when attempting to load Lydia plugin

**Comment by udaythefreelancer** [comment]
bro why dont u check pinned message in userge group t.me/usergeot

**Comment by Phyco-Ninja** [comment]
https://github.com/UsergeTeam/Userge/issues/94#issuecomment-655922393 try this

**Comment by Bilibox** [comment]
> bro why dont u check pinned message in userge group [t.me/usergeot](http://t.me/usergeot)

Because bro i'm not in telegram
Best to switch to discord!

**Comment by rowdy-hero** [comment]
Do False the value of LOAD_UNOFFICIAL_PLUGINS and then update to latest alpha.
Then do Again True value of that var. 🤷🏼

**Comment by Bilibox** [comment]
> Do False the value of LOAD_UNOFFICIAL_PLUGINS and then update to latest alpha.
> Then do Again True value of that var. 🤷🏼

Appreciate it thanks. on latest alpha build already but ig ill try just setting to false then back to true after it boots up

**Comment by Muttahir786** [comment]
> > bro why dont u check pinned message in userge group [t.me/usergeot](http://t.me/usergeot)
> 
> Because bro i'm not in telegram
> Best to switch to discord!

Quick question:
if u r not on telegram why are you running bot?

**Comment by udaythefreelancer** [comment]
> > bro why dont u check pinned message in userge group [t.me/usergeot](http://t.me/usergeot)
> 
> Because bro i'm not in telegram
> Best to switch to discord!

if u not in telegram then how you using userge

**Comment by udaythefreelancer** [comment]
> > bro why dont u check pinned message in userge group [t.me/usergeot](http://t.me/usergeot)
> 
> Because bro i'm not in telegram
> Best to switch to discord!

also i do have discord i use it

**Comment by Bilibox** [comment]
@rowdy-hero Seems like the issue still persists even after doing that.
@udaythefreelancer @Muttahir786 best practice is to not litter an issue with useless commentary. If you are unable to fix the issue or provide advice/workaround for the issue i kindly ask that you stay out of this :) There are chatting programs you can use to chat.

**Comment by Phyco-Ninja** [comment]
> @rowdy-hero Seems like the issue still persists even after doing that.
> @udaythefreelancer @Muttahir786 best practice is to not litter an issue with useless commentary. If you are unable to fix the issue or provide advice/workaround for the issue i kindly ask that you stay out of this :) There are chatting programs you can use to chat.

Still 🤔🤔 It should be fixed if you are on latest Alpha Version

**Comment by Bilibox** [comment]
Yep currently on 
https://github.com/UsergeTeam/Userge/commit/1a28bff43b7c60769344fbd31f53ebc9b2ae7075

**Comment by rking32** [comment]
@Bilibox restart and try [this](https://github.com/UsergeTeam/Userge-Plugins/issues/80#issuecomment-658111326) again. should work fine

**Comment by Bilibox** [comment]
Worked now after latest commit. Thanks
